// Generated by https://quicktype.io

export interface Data {
    message: string;
    status: false;
}

export interface OtpData {
    message: string;
    status: true;
}

// Generated by https://quicktype.io

export interface LoginData {
    profileTime: number;
    secretKey: string;
    subscriberType: string;
    language: string;
    accessToken: string;
    appsflyerMsisdn: string;
    callPlan: string;
    balance: string;
    creditLimit: string;
    msisdn: string;
    profileColor: string;
    status: true;
}
// Generated by https://quicktype.io

export interface AccountData {
    balanceOnNet: string;
    profileName: string;
    lastLogin: string;
    profileTime: number;
    balanceTotal: string;
    dueDateHybrid: string;
    dukcapilName: string;
    firstLogin: string;
    profileHobby: string;
    dueDate: string;
    callPlan: string;
    sumOfBonuses: SumOfBonuses;
    balance: string;
    balanceDetails: BalanceDetails;
    creditLimit: string;
    msisdn: string;
    profileColor: string;
    balanceOffNet: string;
    balanceTrims: string;
    dukcapilUrl: string;
    email: string;
    customerSegmentation: CustomerSegmentation;
    statusSubscription: boolean;
    packageProductList: any[];
    activePackages: null;
    subscriberType: string;
    emailHybrid: string;
    birthDate: null;
    packageList: PackageList[];
    cashback: string;
    profilePicture: string;
    packageProductGroupList: null;
    balanceOnAndOffNet: string;
    maxPullNotification: number;
    validity: string;
    creditLimitHybrid: string;
    status: true;
}

interface BalanceDetails {
    balance: Balance;
    balanceOnNet: BalanceOnNet;
    balanceOffnet: BalanceOffnet;
    balanceOnAndOffNet: null;
}

interface Balance {
    title: string;
    value: string;
}

interface BalanceOffnet {
    detail: BalanceOffnetDetail;
    title: string;
    value: string;
}

interface BalanceOffnetDetail {
    "Sisa Pulsa": string;
}

interface BalanceOnNet {
    detail: BalanceOnNetDetail;
    title: string;
    value: string;
}

interface BalanceOnNetDetail {
    "Masa Berlaku": string;
    "Sisa Pulsa": string;
}

interface CustomerSegmentation {
    segmentationName: string;
    title: string;
    description: string;
    deeplink: null;
}

interface PackageList {
    isRenewable: boolean;
    isProductBuy: boolean;
    isMore: boolean;
    isShareQuota: boolean;
    name: string;
    linkProductBuyType: string;
    linkProductBuyValue: string;
    productId: null;
    detail: DetailElement[];
    groupId: string;
}

interface DetailElement {
    validity: string;
    value: string;
    valueOriginal: null;
}

interface SumOfBonuses {
    Data: string;
    Voice: string;
    SMS: string;
}
