// Generated by https://quicktype.io

export interface CreateResponse {
    title: string;
    participants: Participant[];
    external_id: string;
    created: string;
    last_interaction: null;
    type: string;
    description: string;
    speech: null;
}

interface Participant {
    user: User;
    is_human: boolean;
    name: string;
}

interface User {
    username: string;
    id: number;
    first_name: string;
    account: Account | null;
    is_staff: boolean;
}

interface Account {
    name: string;
    avatar_type: string;
    onboarding_complete: boolean;
    avatar_file_name: string;
}

// Generated by https://quicktype.io

export interface TextResponse {
    replies: Reply[];
    src_char: SrcChar;
    is_final_chunk: boolean;
}

interface Reply {
    text: string;
    id: number;
}

interface SrcChar {
    participant: TextParticipant;
    avatar_file_name: string;
}

interface TextParticipant {
    name: string;
}
